name: 💡 Feature request
description: Got a suggestion for a new idea/feature ?
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief explanation of the feature.
    validations:
      required: true

  - type: textarea
    id: whatsnew
    attributes:
      label: What's new?
      description: If the proposal involves a new component or a redesign of a previous component.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why are we doing this? What use cases does it support? What is the expected outcome?
    validations:
      required: true

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

